// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1THhaj5aGD7gmLRcmUbn27f4Ynl35eSg',
    appId: '1:398760642952:web:98e5d42334b30b0d5d923d',
    messagingSenderId: '398760642952',
    projectId: 'trail-2f143',
    authDomain: 'trail-2f143.firebaseapp.com',
    storageBucket: 'trail-2f143.appspot.com',
    measurementId: 'G-609L3VF0D9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2egOLETnxx4omSAvotzDc8GZ1uTyNnfA',
    appId: '1:398760642952:android:cb94cd877beb04025d923d',
    messagingSenderId: '398760642952',
    projectId: 'trail-2f143',
    storageBucket: 'trail-2f143.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQMt5m8F7j24ADVIzHv5F6L5HcIdUEcGA',
    appId: '1:398760642952:ios:4d8d130ce78cbc795d923d',
    messagingSenderId: '398760642952',
    projectId: 'trail-2f143',
    storageBucket: 'trail-2f143.appspot.com',
    iosBundleId: 'com.example.malabargold',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQMt5m8F7j24ADVIzHv5F6L5HcIdUEcGA',
    appId: '1:398760642952:ios:eb3ba4f15f4429005d923d',
    messagingSenderId: '398760642952',
    projectId: 'trail-2f143',
    storageBucket: 'trail-2f143.appspot.com',
    iosBundleId: 'com.example.malabargold.RunnerTests',
  );
}
